export default {
  grid: {
    container: "130rem",
    gutter: "3.2rem",
  },
  border: {
    radius: "2rem",
  },
  font: {
    family:
      "Quicksand, BlinkMacSystemFont, Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
    light: 300,
    normal: 400,
    bold: 600,
    sizes: {
      xxsmall: "1rem",
      xsmall: "1.2rem",
      small: "1.4rem",
      medium: "1.6rem",
      large: "1.8rem",
      xlarge: "2.0rem",
      xxlarge: "2.8rem",
      xxxlarge: "4rem",
      huge: "5.2rem",
    },
  },
  colors: {
    primary: "#2E4C60",
    lightPrimary: "#426d8a",
    secondary: "#FFCE5C",
    lightSecondary: "#FFBC1F",
    white: "#ffffff",
    black: "#1C1F21",
    gray: "#4C5357",
    lightGray: "#DEE1E3",
    darkGray: "#353630",
    mainBg: "#242529",
    secondaryBg: "#fefeff",
    failed: "#DC3318",
    sucess: "#00A357",
  },
  spacings: {
    xxsmall: "0.8rem",
    xsmall: "1.6rem",
    small: "2.4rem",
    medium: "3.2rem",
    large: "4.0rem",
    xlarge: "4.8rem",
    xxlarge: "5.6rem",
  },
  layers: {
    base: 10,
    menu: 20,
    overlay: 30,
    modal: 40,
    dropDown: 50,
    alwaysOnTop: 60,
  },
  transition: {
    default: "0.3s ease-in-out",
    fast: "0.1s ease-in-out",
  },
} as const;
